<?php

namespace Modules\Auth\App\Controllers;

use Illuminate\Auth\Events\Verified;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Auth\App\Models\User;

/**
 * @tags Auth
 */
class EmailVerificationController extends Controller
{
    /**
     * Verify Email
     *
     * Verifies the user's email address using a signed URL sent by email.
     * The full URL (including `signature` and `expires` query params) is generated by the backend.
     *
     * Typical flow: user clicks the link in their email, the frontend intercepts it
     * and calls this endpoint with the full signed URL.
     *
     * @unauthenticated
     *
     * @response 200 {
     *   "message": "Email verified successfully"
     * }
     * @response 200 scenario="Already verified" {
     *   "message": "Email is already verified"
     * }
     */
    public function verify(Request $request, int $id, string $hash): JsonResponse
    {
        $user = User::findOrFail($id);

        if (! hash_equals(sha1($user->getEmailForVerification()), $hash)) {
            abort(403);
        }

        if ($user->hasVerifiedEmail()) {
            return response()->json([
                'message' => __('auth::auth.email_already_verified'),
            ]);
        }

        $user->markEmailAsVerified();

        event(new Verified($user));

        return response()->json([
            'message' => __('auth::auth.email_verified'),
        ]);
    }

    /**
     * Resend Verification Email
     *
     * Sends a new verification email to the authenticated user.
     * Returns a success message even if the email is already verified.
     *
     * @response 200 {
     *   "message": "Verification link sent"
     * }
     * @response 200 scenario="Already verified" {
     *   "message": "Email is already verified"
     * }
     */
    public function resend(Request $request): JsonResponse
    {
        $user = $request->user();

        if ($user->hasVerifiedEmail()) {
            return response()->json([
                'message' => __('auth::auth.email_already_verified'),
            ]);
        }

        $user->sendEmailVerificationNotification();

        return response()->json([
            'message' => __('auth::auth.verification_sent'),
        ]);
    }
}
